import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSession, signOut } from "next-auth/react";
import Link from "next/link";
export default function Home() {
  const { data: session } = useSession();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? (
        <>
          <p>{session.user.email}</p>
          <Image src={session?.user.image} width="20px" height="20px" />
          <button
            onClick={(e) => {
              e.preventDefault();
              signOut();
            }}
          >
            Sign Out
          </button>
        </>
      ) : (
        <Link href="/signIn">
          <button>Sign In</button>
        </Link>
      )}
      <button
        onClick={() => {
          console.log(session);
        }}
      >
        BTN
      </button>
    </div>
  );
}

// export async function getServerSideProps() {
//   // console.log(process.env.MONGODB_URI, "uri");
//   // env variables can only be accessed through APIs or getting static/server props
//   return { props: { data: "data" } };
// }
